# Generated by Django 3.1 on 2020-08-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='licitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conlicitacao', models.IntegerField()),
                ('orgao_uasg', models.CharField(blank=True, max_length=6, null=True)),
                ('orgao_endereco', models.CharField(blank=True, max_length=150, null=True)),
                ('orgao_cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('orgao_estado', models.CharField(blank=True, max_length=2, null=True)),
                ('orgao_cep', models.CharField(blank=True, max_length=9, null=True)),
                ('edital', models.CharField(blank=True, max_length=20, null=True)),
                ('edital_site', models.CharField(blank=True, max_length=255, null=True)),
                ('edital_homepage', models.CharField(blank=True, max_length=255, null=True)),
                ('edital_homepage2', models.CharField(blank=True, max_length=255, null=True)),
                ('edital_preco', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('edital_tem', models.BooleanField()),
                ('edital_status_id', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('processo', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('itens', models.TextField(blank=True, null=True)),
                ('datahora_prazo', models.DateTimeField(blank=True, null=True)),
                ('datahora_abertura', models.DateTimeField(blank=True, null=True)),
                ('datahora_retirada', models.DateTimeField(blank=True, null=True)),
                ('datahora_visita', models.DateTimeField(blank=True, null=True)),
                ('datahora_documento', models.DateTimeField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('objeto', models.TextField()),
                ('observacao', models.TextField()),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('bidding_id', models.IntegerField()),
                ('has_electronic_trading', models.BooleanField()),
            ],
        ),
    ]
