# Generated by Django 3.1 on 2020-08-27 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=150)),
                ('cnpj', models.IntegerField()),
                ('endereco', models.CharField(blank=True, max_length=150, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('situacao', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('natureza', models.CharField(blank=True, max_length=50, null=True)),
                ('abertura', models.DateField(blank=True, null=True)),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('segmento', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conlicitacao', models.IntegerField()),
                ('orgao_uasg', models.CharField(blank=True, max_length=6, null=True)),
                ('orgao_endereco', models.CharField(blank=True, max_length=150, null=True)),
                ('orgao_cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('orgao_estado', models.CharField(blank=True, max_length=2, null=True)),
                ('orgao_cep', models.CharField(blank=True, max_length=9, null=True)),
                ('edital', models.CharField(blank=True, max_length=20, null=True)),
                ('edital_site', models.URLField(blank=True, max_length=255, null=True)),
                ('edital_homepage', models.CharField(blank=True, max_length=255, null=True)),
                ('edital_homepage2', models.CharField(blank=True, max_length=255, null=True)),
                ('edital_preco', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('edital_tem', models.BooleanField()),
                ('edital_status_id', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('processo', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('itens', models.TextField(blank=True, null=True)),
                ('datahora_prazo', models.DateTimeField(blank=True, null=True)),
                ('datahora_abertura', models.DateTimeField(blank=True, null=True)),
                ('datahora_retirada', models.DateTimeField(blank=True, null=True)),
                ('datahora_visita', models.DateTimeField(blank=True, null=True)),
                ('datahora_documento', models.DateTimeField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('objeto', models.TextField()),
                ('observacao', models.TextField()),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('bidding_id', models.IntegerField()),
                ('has_electronic_trading', models.BooleanField()),
                ('public_body', models.CharField(blank=True, max_length=150, null=True)),
                ('modality', models.CharField(blank=True, max_length=150, null=True)),
                ('arquivo_edital', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'licitações',
                'ordering': ['data_validade'],
                'unique_together': {('id_conlicitacao',)},
            },
        ),
        migrations.CreateModel(
            name='EmpresaLicita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licitacao_empresa', to='conlicita_app.empresa')),
                ('licitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licitacao_empresa', to='conlicita_app.licitacao')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='my_bidding',
            field=models.ManyToManyField(blank=True, related_name='licita_list', through='conlicita_app.EmpresaLicita', to='conlicita_app.Licitacao'),
        ),
        migrations.AlterUniqueTogether(
            name='empresa',
            unique_together={('cnpj',)},
        ),
    ]
