# Generated by Django 3.1 on 2020-08-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conlicita_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacao',
            name='modality',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='licitacao',
            name='public_body',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
