# Generated by Django 3.1 on 2020-08-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conlicita_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresalicita',
            name='garantia_proposta',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='empresalicita',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresalicita',
            name='visita_tecnica',
            field=models.NullBooleanField(verbose_name='visita'),
        ),
    ]
