# Generated by Django 3.1 on 2020-08-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conlicita_app', '0002_auto_20200827_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresalicita',
            name='cadastro',
            field=models.NullBooleanField(verbose_name='fazer cadastro?'),
        ),
        migrations.AddField(
            model_name='empresalicita',
            name='consorcio',
            field=models.NullBooleanField(verbose_name='cabe consórcio?'),
        ),
        migrations.AddField(
            model_name='empresalicita',
            name='orcamento_data_base',
            field=models.DateField(blank=True, null=True, verbose_name='data base da planilha'),
        ),
        migrations.AddField(
            model_name='empresalicita',
            name='prazo_execucao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='prazo de execução da obra'),
        ),
        migrations.AddField(
            model_name='empresalicita',
            name='qualificacao_tecnica',
            field=models.NullBooleanField(verbose_name='qualificação técnica'),
        ),
        migrations.AddField(
            model_name='empresalicita',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Participar'), ('2', 'Acompanhar'), ('3', 'Descartada')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='empresalicita',
            name='garantia_proposta',
            field=models.NullBooleanField(verbose_name='garantia de proposta'),
        ),
        migrations.AlterField(
            model_name='empresalicita',
            name='visita_tecnica',
            field=models.NullBooleanField(verbose_name='visita técnica'),
        ),
    ]
