# Generated by Django 3.1 on 2020-08-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conlicita_app', '0002_auto_20200809_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=150)),
                ('cnpj', models.IntegerField()),
                ('endereco', models.CharField(blank=True, max_length=150, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('situacao', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('natureza', models.CharField(blank=True, max_length=50, null=True)),
                ('abertura', models.DateField(blank=True, null=True)),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('segmento', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='licitacao',
            options={'verbose_name_plural': 'licitações'},
        ),
    ]
