# Generated by Django 3.1 on 2020-08-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conlicita_app', '0005_auto_20200810_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licitacao',
            options={'ordering': ['data_validade'], 'verbose_name_plural': 'licitações'},
        ),
        migrations.AlterField(
            model_name='licitacao',
            name='edital',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
